version: '3'
services:
  landbot-service:
    image: landbot-challenge:latest
    build:
      context: .
      args:
        APP_ENV: 'local'
      dockerfile: ./Dockerfile
    stop_signal: SIGINT
    command: python ./src/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file:
      - .env.local
    networks:
      - landbot-net
    volumes:
      - ./:/code

  landbot-redis:
    image: redis:5-alpine
    volumes:
      - redis-data:/data
    networks:
      - landbot-net
    ports:
      - "6379:6379"

  landbot-postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: landbot
      POSTGRES_PASSWORD: landbot
      POSTGRES_DB: landbot-db
    command: -c fsync=off
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - landbot-net
    ports:
      - "5432:5432"


networks:
  landbot-net: {}


volumes:
  pgdata: {}
  redis-data: {}
