# Generated by Django 4.2.2 on 2023-07-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0001_initial"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="topics.topic"
            ),
        ),
    ]
